osamhack2022/WEB_MoGoon_PatAndMat

.vscode/settings.json
WEB(FE)/mogoon/src/App.css
WEB(FE)/mogoon/src/App.js
WEB(FE)/mogoon/src/components/Header/Header.js
WEB(FE)/mogoon/src/components/Header/HeaderItem.js
WEB(FE)/mogoon/src/components/banner.js
WEB(FE)/mogoon/src/css/Header.css
WEB(FE)/mogoon/src/css/banner.css
WEB(FE)/mogoon/src/index.css

main page 

---

WEB(FE)/mogoon/public/img/etc/saveOff.svg
WEB(FE)/mogoon/public/img/etc/saveOn.svg
WEB(FE)/mogoon/src/App.css
WEB(FE)/mogoon/src/components/Specialty/Specialty.js
WEB(FE)/mogoon/src/components/Specialty/SpecialtyItem.js
WEB(FE)/mogoon/src/css/Header.css
WEB(FE)/mogoon/src/css/Specialty.css

Specialty Update 
특기아이템들 사이즈 px -> % 변경하기
리덕스 사용
express랑 연결 및 데이터 바인딩
concurrently사용할것

Specialty Update

---

WEB(BE)/controller/ctrl.speciality.js
WEB(BE)/router/speciality.js
WEB(BE)/view/add_speciality.html
WEB(BE)/view/add_speciality_desc.html

특기 디비 구조를 군종 별로 특기를 저장하도록 수정하여 그에 맞게
디비 구조를 수정하고, 특기 수정 폼도 수정하였습니다.

FEAT : 특기 상세 페이지 데이터 입력 폼 추가 & 특기 추가 폼 수정

---

WEB(BE)/controller/ctrl.speciality.js

데이터베이스에서 특기 상세 데이터를 저장하는 구조를 변경하였습니다.
변경한 구조에 맞게 데이터를 불러오도록 API를 수정하였습니다.

FIX : 바뀐 데이터베이스 구조에 맞게 API 변경

---

WEB(BE)/controller/ctrl.speciality.js
WEB(BE)/router/speciality.js

특기별 상세 페이지에서 의견을 조회하고 생성하는 API를 추가했습니다.
자세한 내용은 백엔드 리드미를 참고해주세요.

FEAT : 의견 조회,생성 API 추가

---

WEB(BE)/controller/ctrl.speciality.qna.js
WEB(BE)/router/speciality.js

FEAT : QNA 조회 및 생성 API 추가

---

WEB(FE)/mogoon/src/components/Account/Join.js
WEB(FE)/mogoon/src/components/Account/Login.js
WEB(FE)/mogoon/src/components/Enlist/Enlist.js
WEB(FE)/mogoon/src/components/Header/Header.js
WEB(FE)/mogoon/src/components/Specialty/SpDetail.js
WEB(FE)/mogoon/src/components/Specialty/Specialty.js
WEB(FE)/mogoon/src/components/Specialty/SpecialtyItem.js
WEB(FE)/mogoon/src/css/Enlist.css
WEB(FE)/mogoon/src/css/SpDetail.css
WEB(FE)/mogoon/src/css/Specialty.css

군지원 content3 수정
로그인 회원가입 유효성검사 업데이트
특기, 특기자세히 데이터 state 화면에 표시

UPDATE : Enlist, Account, Specialty

---

WEB(FE)/mogoon/package-lock.json
WEB(FE)/mogoon/package.json
WEB(FE)/mogoon/src/components/Enlist/Enlist.js
WEB(FE)/mogoon/src/components/Specialty/SpDetail.js
WEB(FE)/mogoon/src/components/Specialty/Specialty.js
WEB(FE)/mogoon/src/css/Enlist.css
WEB(FE)/mogoon/src/css/SpDetail.css

특기소개 : 스켈레톤 추가
특기 자세히 : Loading 추가
군지원 UX 업데이트중

UPDATE : Specialty, SpDetail, Enlist

---

WEB(FE)/mogoon/src/App.js
WEB(FE)/mogoon/src/components/Account/Login.js
WEB(FE)/mogoon/src/components/Enlist/Enlist.js
WEB(FE)/mogoon/src/components/Header/Header.js
WEB(FE)/mogoon/src/components/Specialty/Specialty.js
WEB(FE)/mogoon/src/index.js
WEB(FE)/mogoon/src/reducer/store.js
WEB(FE)/mogoon/src/reducer/userSlice.js

UPDATE : Login

---

WEB(BE)/app.js
WEB(BE)/controller/ctrl.auth.js
WEB(BE)/controller/ctrl.speciality.js
WEB(BE)/controller/ctrl.user.js
WEB(BE)/router/user.js

1. 인증 요청방식 변경 인증 요청시 Authorization 헤더에 ID Token 값을 통해 인증 여부를 확인합니다.
2. 유저 DB를 작성하고 테스트 데이터를 넣은 후 해당 데이터를 조회하는 API를 작성했습니다.

FEAT : 유저 정보를 불러오는 API 작성 & 인증 확인 방식 변경

---

WEB(FE)/mogoon/src/components/Enlist/Enlist.js
WEB(FE)/mogoon/src/components/Specialty/SpDetail.js
WEB(FE)/mogoon/src/css/Enlist.css

군지원 content1 배너 효과 추가
군지원 content2 아이템 모달 추가

UPDATE : Enlist content1, content2

---

WEB(FE)/mogoon/src/components/Enlist/Enlist.js
WEB(FE)/mogoon/src/components/Specialty/SpDetail.js
WEB(FE)/mogoon/src/css/Enlist.css

UPDATE : Enlist 스탭2 모달

---

WEB(FE)/mogoon/public/index.html
WEB(FE)/mogoon/src/components/Enlist/Enlist.js
WEB(FE)/mogoon/src/css/Enlist.css

UPDATE : Enlist content3

---

WEB(BE)/controller/ctrl.user.js

에러가 발생했을 때 서버가 멈추지 않게 try-catch 적용

FIX : try-catch 적용

---

WEB(FE)/mogoon/src/components/Enlist/Enlist.js
WEB(FE)/mogoon/src/components/Specialty/SpecialtyItem.js

HOTFIX : SpecialtyItem 

---

WEB(FE)/mogoon/src/components/Header/Header.js
WEB(FE)/mogoon/src/components/MyPage/MyEnInfoItem.js
WEB(FE)/mogoon/src/css/Header.css
WEB(FE)/mogoon/src/css/MyPage/Common.css
WEB(FE)/mogoon/src/css/MyPage/MyEnInfoEdit.css
WEB(FE)/mogoon/src/css/MyPage/MyPage.css

1. 헤더 css 중 ul , li 태그 설정이 전역으로 적용되지 않게 분리
2. 모달창 UI 작업

FEAT : 헤더 css 헤더에만 적용되게 분리 & 모달창 UI 작업

---

WEB(FE)/mogoon/src/components/MyPage/MyEnInfoItem.js
WEB(FE)/mogoon/src/css/MyPage/MyEnInfoEdit.css

FEAT : 모달창에서 각 항목 선택 기능 추가

---

README.md
WEB(FE)/mogoon/src/components/Account/Login.js
WEB(FE)/mogoon/src/components/Header/Header.js
WEB(FE)/mogoon/src/components/Specialty/SpDetail.js
WEB(FE)/mogoon/src/components/Specialty/SpecialtyItem.js
WEB(FE)/mogoon/src/css/MyPage/Common.css
WEB(FE)/mogoon/src/css/MyPage/MyEnInfoEdit.css
WEB(FE)/mogoon/src/css/MyPage/MyEnInfoItem.css
WEB(FE)/mogoon/src/css/Specialty.css

FIX : SpDetail opinion

---

WEB(FE)/mogoon/src/components/MyPage/MyPage.js
WEB(FE)/mogoon/src/components/Specialty/Specialty.js
WEB(FE)/mogoon/src/components/Specialty/SpecialtyItem.js

UPDATE : MyPage

---

WEB(FE)/mogoon/src/components/Enlist/Enlist.js
WEB(FE)/mogoon/src/css/Enlist.css

UPDATE : Enlist
